/* DO NOT EDIT, file generated by nestjs-i18n */

/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "notification": {
        "email": {
            "login_verification_code": {
                "title": string;
                "greeting": string;
                "instruction": string;
                "codeValidFor": string;
                "minute": string;
                "doNotShare": string;
                "helpText": string;
                "ignoreMessage": string;
                "footer": string;
                "codeValidity": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
