// Representative slice for Phase 0 — the full ~250-item catalog import
// from the Google Sheet is a Phase 1 migration (see SeederService.seedItems).
//
// The `*Key` fields point at the `seedKey` of the row they belong to, never at
// its name. A manager may rename any of those rows in the panel; the link has
// to survive that.
export default [
  {
    seedKey: 't-shirt',
    itemName: 'T-Shirt',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 800,
  },
  {
    seedKey: 'shirt',
    itemName: 'Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 700,
    priceHigh: 1000,
  },
  {
    seedKey: 'trousers',
    itemName: 'Trousers',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'dress',
    itemName: 'Dress',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'blouse',
    itemName: 'Blouse',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 700,
    priceHigh: 1000,
  },
  {
    seedKey: 'skirt',
    itemName: 'Skirt',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'bedsheet',
    itemName: 'Bedsheet',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'heavy',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'duvet-cover',
    itemName: 'Duvet Cover',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'heavy',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 2000,
    priceHigh: 3000,
  },
  {
    seedKey: 'sneakers',
    itemName: 'Sneakers',
    serviceKey: 'cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'shoes',
    subCategoryKey: 'others',
    priceLow: 2500,
    priceHigh: 4000,
  },
  {
    seedKey: 'baby-onesie',
    itemName: 'Baby Onesie',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 400,
    priceHigh: 600,
  },
];
