// The starter price list: every row of the "Dress Doctor Price List" sheet as
// it stood on 2026-08-12, which is where the counter's prices actually come
// from. Baked into the repository rather than read from the sheet at seed
// time, so a seed run needs no Google credentials and a price change arrives
// as a reviewed commit.
//
// Prices are the low/high pair; the unit price the counter starts from is the
// midpoint, derived by `itemUnitPrice` rather than stored here.
//
// The `*Key` fields point at the `seedKey` of the row they belong to, never at
// its name. A manager may rename any of those rows in the panel; the link has
// to survive that. An item's own `seedKey` carries its filing — `men-bottoms-
// hoodie` — because the sheet prices the same garment differently depending on
// who wears it, so the name alone does not identify a row.
export default [
  {
    seedKey: 'men-tops-t-shirt',
    itemName: 'T-Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'men-tops-shirt',
    itemName: 'Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'men-tops-polo-shirt',
    itemName: 'Polo Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'men-tops-dress-shirt',
    itemName: 'Dress Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'men-tops-casual-shirt',
    itemName: 'Casual Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'men-tops-tank-top',
    itemName: 'Tank Top',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 200,
    priceHigh: 400,
  },
  {
    seedKey: 'men-tops-sweatshirt',
    itemName: 'Sweatshirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 700,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-tops-hoodie',
    itemName: 'Hoodie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-tops-sweater',
    itemName: 'Sweater',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-tops-cardigan',
    itemName: 'Cardigan',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-tops-vest-waistcoat',
    itemName: 'Vest (Waistcoat)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 700,
  },
  {
    seedKey: 'men-tops-traditional-top-kaftan-top-etc',
    itemName: 'Traditional Top (Kaftan top, etc.)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 2000,
    priceHigh: 3000,
  },
  {
    seedKey: 'men-tops-sport-wear-jersey',
    itemName: 'Sport Wear/ Jersey',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'men-tops-sweater-vest',
    itemName: 'Sweater Vest',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 500,
  },
  {
    seedKey: 'men-tops-waistcoat',
    itemName: 'Waistcoat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 500,
  },
  {
    seedKey: 'men-bottoms-hoodie',
    itemName: 'Hoodie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 900,
  },
  {
    seedKey: 'men-bottoms-jeans',
    itemName: 'Jeans',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 900,
  },
  {
    seedKey: 'men-bottoms-cargo-trousers',
    itemName: 'Cargo Trousers',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 300,
    priceHigh: 600,
  },
  {
    seedKey: 'men-bottoms-formal-trousers',
    itemName: 'Formal Trousers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'men-bottoms-khaki-trousers',
    itemName: 'Khaki trousers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'men-bottoms-chinos',
    itemName: 'Chinos',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 800,
    priceHigh: 1200,
  },
  {
    seedKey: 'men-bottoms-shorts',
    itemName: 'Shorts',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'men-bottoms-joggers',
    itemName: 'Joggers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-bottoms-sweatpants',
    itemName: 'Sweatpants',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-bottoms-traditional-bottom',
    itemName: 'Traditional Bottom',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'bottoms',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'men-full-body-hoodie',
    itemName: 'Hoodie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'men-full-body-suit-2-piece',
    itemName: 'Suit (2-piece)',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'men-full-body-suit-3-piece',
    itemName: 'Suit (3-piece)',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 5250,
    priceHigh: 6750,
  },
  {
    seedKey: 'men-full-body-blazer',
    itemName: 'Blazer',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'men-full-body-jumpsuit',
    itemName: 'Jumpsuit',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'men-full-body-overalls',
    itemName: 'Overalls',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-full-body-agbada',
    itemName: 'Agbada',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'men-full-body-complete-traditional-outfit',
    itemName: 'Complete Traditional Outfit',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 2000,
    priceHigh: 3500,
  },
  {
    seedKey: 'men-full-body-senator-wear',
    itemName: 'Senator Wear',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'premium',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 2500,
    priceHigh: 3000,
  },
  {
    seedKey: 'men-full-body-tracksuit',
    itemName: 'Tracksuit',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'men-full-body-lounge-set-2-piece',
    itemName: 'Lounge Set (2-piece)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'men-full-body-kaftan',
    itemName: 'Kaftan',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'men-full-body-white-lab-coat',
    itemName: 'White Lab Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'men-outerwear-casual-jacket',
    itemName: 'Casual Jacket',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'outerwear',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'men-outerwear-leather-jacket',
    itemName: 'Leather Jacket',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'men',
    subCategoryKey: 'outerwear',
    priceLow: 2250,
    priceHigh: 3750,
  },
  {
    seedKey: 'men-outerwear-suit-jacket',
    itemName: 'Suit Jacket',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'men',
    subCategoryKey: 'outerwear',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'men-outerwear-coat',
    itemName: 'Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'outerwear',
    priceLow: 2500,
    priceHigh: 4000,
  },
  {
    seedKey: 'men-outerwear-winter-coat',
    itemName: 'Winter Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'men',
    subCategoryKey: 'outerwear',
    priceLow: 3000,
    priceHigh: 5200,
  },
  {
    seedKey: 'men-outerwear-raincoat',
    itemName: 'Raincoat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'outerwear',
    priceLow: 2500,
    priceHigh: 4000,
  },
  {
    seedKey: 'men-outerwear-tie',
    itemName: 'Tie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'men',
    subCategoryKey: 'outerwear',
    priceLow: 100,
    priceHigh: 100,
  },
  {
    seedKey: 'men-sleepwear-pajamas-set',
    itemName: 'Pajamas (Set)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'sleepwear',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-sleepwear-night-shorts',
    itemName: 'Night Shorts',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'sleepwear',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'men-sleepwear-robe',
    itemName: 'Robe',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'sleepwear',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'men-undergarments-boxer',
    itemName: 'Boxer',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'undergarments',
    priceLow: 200,
    priceHigh: 400,
  },
  {
    seedKey: 'men-undergarments-brief',
    itemName: 'Brief',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'undergarments',
    priceLow: 200,
    priceHigh: 400,
  },
  {
    seedKey: 'men-undergarments-undershirt-inner-wear',
    itemName: 'Undershirt / Inner wear',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'undergarments',
    priceLow: 400,
    priceHigh: 600,
  },
  {
    seedKey: 'men-casual-men-s-caps',
    itemName: "Men's Caps",
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'casual',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'men-casual-socks-set',
    itemName: 'Socks (Set)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'casual',
    priceLow: 50,
    priceHigh: 100,
  },
  {
    seedKey: 'men-casual-neck-pillow',
    itemName: 'Neck pillow',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'men',
    subCategoryKey: 'casual',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'women-tops-blouse',
    itemName: 'Blouse',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-tops-polo-shirt',
    itemName: 'Polo Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'women-tops-shirt',
    itemName: 'Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 700,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-tops-t-shirt',
    itemName: 'T-Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 800,
  },
  {
    seedKey: 'women-tops-tank-top',
    itemName: 'Tank Top',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-tops-crop-top',
    itemName: 'Crop Top',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-tops-bodysuit',
    itemName: 'Bodysuit',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'women-tops-sweater',
    itemName: 'Sweater',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-tops-cardigan',
    itemName: 'Cardigan',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-tops-hoodie',
    itemName: 'Hoodie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-tops-sport-wear-jersey',
    itemName: 'Sport Wear/ Jersey',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'women-tops-nightie',
    itemName: 'Nightie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'women-tops-sport-tops',
    itemName: 'Sport Tops',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 500,
  },
  {
    seedKey: 'women-tops-sport-bra',
    itemName: 'Sport Bra',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'women-tops-dress-shirt',
    itemName: 'Dress Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 500,
  },
  {
    seedKey: 'women-tops-knitted-top',
    itemName: 'Knitted Top',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'women-tops-sweater-vest',
    itemName: 'Sweater Vest',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 500,
  },
  {
    seedKey: 'women-tops-waistcoat',
    itemName: 'Waistcoat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'tops',
    priceLow: 500,
    priceHigh: 500,
  },
  {
    seedKey: 'women-bottoms-jeans',
    itemName: 'Jeans',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 800,
    priceHigh: 1200,
  },
  {
    seedKey: 'women-bottoms-palazzo-trousers',
    itemName: 'Palazzo trousers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 800,
  },
  {
    seedKey: 'women-bottoms-khaki-trousers',
    itemName: 'Khaki trousers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'women-bottoms-formal-trousers',
    itemName: 'Formal Trousers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'women-bottoms-sport-pants-and-leggings',
    itemName: 'Sport pants & Leggings',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 500,
  },
  {
    seedKey: 'women-bottoms-skirt-short',
    itemName: 'Skirt (Short)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'women-bottoms-skirt-long',
    itemName: 'Skirt (Long)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-bottoms-shorts',
    itemName: 'Shorts',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'women-bottoms-joggers',
    itemName: 'Joggers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-bottoms-nightie',
    itemName: 'Nightie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'bottoms',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'women-dresses-short-dress',
    itemName: 'Short Dress',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-dresses-long-dress',
    itemName: 'Long Dress',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'women-dresses-evening-gown',
    itemName: 'Evening Gown',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'women-dresses-wedding-dress',
    itemName: 'Wedding Dress',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 15000,
    priceHigh: 30000,
  },
  {
    seedKey: 'women-dresses-traditional-dress',
    itemName: 'Traditional Dress',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 1200,
    priceHigh: 2000,
  },
  {
    seedKey: 'women-dresses-jumpsuit',
    itemName: 'Jumpsuit',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'women-dresses-playsuit',
    itemName: 'Playsuit',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'women-dresses-corporate-gown',
    itemName: 'Corporate Gown',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 1500,
    priceHigh: 3000,
  },
  {
    seedKey: 'women-dresses-casual-gown',
    itemName: 'Casual Gown',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'dresses',
    priceLow: 1000,
    priceHigh: 2000,
  },
  {
    seedKey: 'women-full-sets-suit-female',
    itemName: 'Suit (Female)',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'full-sets',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'women-full-sets-two-piece-set',
    itemName: 'Two-piece Set',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-sets',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-full-sets-kaftan',
    itemName: 'Kaftan',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-sets',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'women-full-sets-boubou',
    itemName: 'Boubou',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-sets',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'women-full-sets-traditional-complete-outfit',
    itemName: 'Traditional Complete Outfit',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-sets',
    priceLow: 2000,
    priceHigh: 3500,
  },
  {
    seedKey: 'women-full-sets-gym-wear-2-piece',
    itemName: 'Gym Wear 2 piece',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-sets',
    priceLow: 1000,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-full-sets-gym-wear-3-piece',
    itemName: 'Gym Wear 3 piece',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-sets',
    priceLow: 1500,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-outerwear-blazer',
    itemName: 'Blazer',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'women-outerwear-jacket',
    itemName: 'Jacket',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'women-outerwear-coat',
    itemName: 'Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 2500,
    priceHigh: 4000,
  },
  {
    seedKey: 'women-outerwear-trench-coat',
    itemName: 'Trench Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 2500,
    priceHigh: 4000,
  },
  {
    seedKey: 'women-outerwear-fur-coat',
    itemName: 'Fur Coat',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 3750,
    priceHigh: 6000,
  },
  {
    seedKey: 'women-outerwear-scarf',
    itemName: 'Scarf',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 200,
    priceHigh: 300,
  },
  {
    seedKey: 'women-outerwear-suit-jacket',
    itemName: 'Suit Jacket',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-outerwear-head-bands',
    itemName: 'Head Bands',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'women-outerwear-tie',
    itemName: 'Tie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'women',
    subCategoryKey: 'outerwear',
    priceLow: 100,
    priceHigh: 100,
  },
  {
    seedKey: 'women-special-items-lingerie',
    itemName: 'Lingerie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'special-items',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-special-items-bra',
    itemName: 'Bra',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'special-items',
    priceLow: 300,
    priceHigh: 600,
  },
  {
    seedKey: 'women-special-items-panties',
    itemName: 'Panties',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'special-items',
    priceLow: 200,
    priceHigh: 400,
  },
  {
    seedKey: 'women-special-items-shapewear',
    itemName: 'Shapewear',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'special-items',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-sleepwear-nightgown',
    itemName: 'Nightgown',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'sleepwear',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-sleepwear-pajamas',
    itemName: 'Pajamas',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'sleepwear',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'women-sleepwear-robe-cord',
    itemName: 'Robe Cord',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'sleepwear',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'women-casual-women-s-caps',
    itemName: "Women's Caps",
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'casual',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'women-casual-hair-bonnet',
    itemName: 'Hair Bonnet',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'casual',
    priceLow: 200,
    priceHigh: 300,
  },
  {
    seedKey: 'women-casual-socks-set',
    itemName: 'Socks (Set)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'casual',
    priceLow: 50,
    priceHigh: 100,
  },
  {
    seedKey: 'women-casual-ankara-fabric-2-yard',
    itemName: 'Ankara Fabric (2 yard)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'casual',
    priceLow: 400,
    priceHigh: 600,
  },
  {
    seedKey: 'women-full-body-lounge-set-2-piece',
    itemName: 'Lounge Set (2-piece)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-full-body-tracksuit',
    itemName: 'Tracksuit',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-full-body-suit-2-piece',
    itemName: 'Suit (2-piece)',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'full-body',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'women-full-body-suit-3-piece',
    itemName: 'Suit (3-piece)',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'women',
    subCategoryKey: 'full-body',
    priceLow: 2500,
    priceHigh: 3000,
  },
  {
    seedKey: 'women-full-body-nightie-2-piece',
    itemName: 'Nightie (2-piece)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-full-body-white-lab-coat',
    itemName: 'White Lab Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'women-undergarments-undershirt-inner-wear',
    itemName: 'Undershirt / Inner wear',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'undergarments',
    priceLow: 400,
    priceHigh: 600,
  },
  {
    seedKey: 'women-casual-neck-pillow',
    itemName: 'Neck pillow',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'women',
    subCategoryKey: 'casual',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-tops-t-shirt',
    itemName: 'T-Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 300,
    priceHigh: 450,
  },
  {
    seedKey: 'children-tops-dress-shirt',
    itemName: 'Dress Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 200,
    priceHigh: 400,
  },
  {
    seedKey: 'children-tops-shirt',
    itemName: 'Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 400,
    priceHigh: 600,
  },
  {
    seedKey: 'children-tops-school-shirt',
    itemName: 'School Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 400,
    priceHigh: 600,
  },
  {
    seedKey: 'children-tops-sweater',
    itemName: 'Sweater',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'children-tops-hoodie',
    itemName: 'Hoodie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    seedKey: 'children-tops-polo-shirt',
    itemName: 'Polo Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-tops-nightie',
    itemName: 'Nightie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-tops-tank-top',
    itemName: 'Tank Top',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-tops-sport-wear-jersey',
    itemName: 'Sport Wear/ Jersey',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-tops-sweater-vest',
    itemName: 'Sweater Vest',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'tops',
    priceLow: 200,
    priceHigh: 300,
  },
  {
    seedKey: 'children-bottoms-sport-wear-jersey',
    itemName: 'Sport Wear/ Jersey',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-bottoms-nightie',
    itemName: 'Nightie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-bottoms-shorts',
    itemName: 'Shorts',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 300,
    priceHigh: 600,
  },
  {
    seedKey: 'children-bottoms-trousers',
    itemName: 'Trousers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 450,
    priceHigh: 700,
  },
  {
    seedKey: 'children-bottoms-jeans',
    itemName: 'Jeans',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 450,
    priceHigh: 700,
  },
  {
    seedKey: 'children-bottoms-skirt',
    itemName: 'Skirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 300,
    priceHigh: 600,
  },
  {
    seedKey: 'children-bottoms-waist-coat',
    itemName: 'Waist Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'children-bottoms-sweatpants',
    itemName: 'Sweatpants',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-bottoms-joggers',
    itemName: 'Joggers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 200,
    priceHigh: 300,
  },
  {
    seedKey: 'children-bottoms-host',
    itemName: 'Host',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'bottoms',
    priceLow: 100,
    priceHigh: 100,
  },
  {
    seedKey: 'children-full-school-uniform-complete-set',
    itemName: 'School Uniform (Complete Set)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full',
    priceLow: 300,
    priceHigh: 600,
  },
  {
    seedKey: 'children-full-dress',
    itemName: 'Dress',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full',
    priceLow: 700,
    priceHigh: 1200,
  },
  {
    seedKey: 'children-full-jumpsuit',
    itemName: 'Jumpsuit',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'children',
    subCategoryKey: 'full',
    priceLow: 2250,
    priceHigh: 3150,
  },
  {
    seedKey: 'children-full-traditional-wear',
    itemName: 'Traditional Wear',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full',
    priceLow: 900,
    priceHigh: 1500,
  },
  {
    seedKey: 'children-outerwear-jacket',
    itemName: 'Jacket',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'outerwear',
    priceLow: 900,
    priceHigh: 1500,
  },
  {
    seedKey: 'children-outerwear-head-bands',
    itemName: 'Head Bands',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'outerwear',
    priceLow: 100,
    priceHigh: 100,
  },
  {
    seedKey: 'children-outerwear-coat',
    itemName: 'Coat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'outerwear',
    priceLow: 1500,
    priceHigh: 2400,
  },
  {
    seedKey: 'children-outerwear-tie',
    itemName: 'Tie',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'children',
    subCategoryKey: 'outerwear',
    priceLow: 50,
    priceHigh: 50,
  },
  {
    seedKey: 'children-sleepwear-pajamas',
    itemName: 'Pajamas',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'sleepwear',
    priceLow: 300,
    priceHigh: 600,
  },
  {
    seedKey: 'children-casual-socks-set',
    itemName: 'Socks (Set)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'casual',
    priceLow: 100,
    priceHigh: 150,
  },
  {
    seedKey: 'children-casual-socks-single',
    itemName: 'Socks (Single)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'casual',
    priceLow: 50,
    priceHigh: 50,
  },
  {
    seedKey: 'children-casual-children-s-caps',
    itemName: "Children's Caps",
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'casual',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-full-body-suit-2-piece',
    itemName: 'Suit (2-piece)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'premium',
    categoryKey: 'children',
    subCategoryKey: 'full-body',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'children-full-body-suit-3-piece',
    itemName: 'Suit (3-piece)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'premium',
    categoryKey: 'children',
    subCategoryKey: 'full-body',
    priceLow: 1200,
    priceHigh: 1500,
  },
  {
    seedKey: 'children-full-body-sport-wear-jersey',
    itemName: 'Sport Wear/ Jersey',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full-body',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'children-full-body-senator-wear',
    itemName: 'Senator Wear',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full-body',
    priceLow: 300,
    priceHigh: 700,
  },
  {
    seedKey: 'children-full-body-nightie-2-piece',
    itemName: 'Nightie (2-piece)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full-body',
    priceLow: 200,
    priceHigh: 400,
  },
  {
    seedKey: 'children-full-body-lounge-set-2-piece',
    itemName: 'Lounge Set (2-piece)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full-body',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'children-full-body-tracksuit',
    itemName: 'Tracksuit',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'full-body',
    priceLow: 600,
    priceHigh: 600,
  },
  {
    seedKey: 'children-dresses-corporate-gown',
    itemName: 'Corporate Gown',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'children',
    subCategoryKey: 'dresses',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'children-dresses-casual-gown',
    itemName: 'Casual Gown',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'dresses',
    priceLow: 500,
    priceHigh: 700,
  },
  {
    seedKey: 'children-undergarments-undershirt-inner-wear',
    itemName: 'Undershirt / Inner wear',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'children',
    subCategoryKey: 'undergarments',
    priceLow: 200,
    priceHigh: 200,
  },
  {
    seedKey: 'baby-baby-items-baby-romper',
    itemName: 'Baby Romper',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-shirt',
    itemName: 'Baby Shirt',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-trousers',
    itemName: 'Baby Trousers',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-dress',
    itemName: 'Baby Dress',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-pajamas',
    itemName: 'Baby Pajamas',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-jacket',
    itemName: 'Baby Jacket',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-blanket',
    itemName: 'Baby Blanket',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'baby-baby-items-swaddle-cloth',
    itemName: 'Swaddle Cloth',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-bib',
    itemName: 'Bib',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-socks',
    itemName: 'Baby Socks',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'baby-baby-items-baby-hat',
    itemName: 'Baby Hat',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'baby',
    subCategoryKey: 'baby-items',
    priceLow: 200,
    priceHigh: 500,
  },
  {
    seedKey: 'shoes-casual-sneakers',
    itemName: 'Sneakers',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'casual',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'shoes-casual-canvas-shoes',
    itemName: 'Canvas Shoes',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'casual',
    priceLow: 1000,
    priceHigh: 2000,
  },
  {
    seedKey: 'shoes-casual-loafers',
    itemName: 'Loafers',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'casual',
    priceLow: 1000,
    priceHigh: 2000,
  },
  {
    seedKey: 'shoes-formal-leather-shoes',
    itemName: 'Leather Shoes',
    serviceKey: 'cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'shoes',
    subCategoryKey: 'formal',
    priceLow: 2250,
    priceHigh: 4500,
  },
  {
    seedKey: 'shoes-formal-heels',
    itemName: 'Heels',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'formal',
    priceLow: 1000,
    priceHigh: 2000,
  },
  {
    seedKey: 'shoes-formal-corporate-shoes',
    itemName: 'Corporate Shoes',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'formal',
    priceLow: 1000,
    priceHigh: 2000,
  },
  {
    seedKey: 'shoes-others-sandals',
    itemName: 'Sandals',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'others',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'shoes-others-slippers',
    itemName: 'Slippers',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'others',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'shoes-others-boots',
    itemName: 'Boots',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'others',
    priceLow: 2000,
    priceHigh: 3500,
  },
  {
    seedKey: 'shoes-others-ankle-boots',
    itemName: 'Ankle Boots',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'shoes',
    subCategoryKey: 'others',
    priceLow: 2000,
    priceHigh: 3500,
  },
  {
    seedKey: 'shoes-others-suede-shoes',
    itemName: 'Suede Shoes',
    serviceKey: 'cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'shoes',
    subCategoryKey: 'others',
    priceLow: 2250,
    priceHigh: 4500,
  },
  {
    seedKey: 'bags-all-bags-backpack',
    itemName: 'Backpack',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'bags-all-bags-school-bag',
    itemName: 'School Bag',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'bags-all-bags-handbag',
    itemName: 'Handbag',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 1500,
    priceHigh: 3000,
  },
  {
    seedKey: 'bags-all-bags-clutch',
    itemName: 'Clutch',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'bags-all-bags-travel-bag',
    itemName: 'Travel Bag',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 2500,
    priceHigh: 4000,
  },
  {
    seedKey: 'bags-all-bags-gym-bag',
    itemName: 'Gym Bag',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'bags-all-bags-laptop-bag',
    itemName: 'Laptop Bag',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'bags-all-bags-leather-bag',
    itemName: 'Leather Bag',
    serviceKey: 'cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 2250,
    priceHigh: 3750,
  },
  {
    seedKey: 'bags-all-bags-suitcase-small',
    itemName: 'Suitcase (Small)',
    serviceKey: 'cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 3750,
    priceHigh: 6000,
  },
  {
    seedKey: 'bags-all-bags-suitcase-large',
    itemName: 'Suitcase (Large)',
    serviceKey: 'cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'bags',
    subCategoryKey: 'all-bags',
    priceLow: 6000,
    priceHigh: 9000,
  },
  {
    seedKey: 'household-bedding-bedsheet-single',
    itemName: 'Bedsheet (Single)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 800,
    priceHigh: 1200,
  },
  {
    seedKey: 'household-bedding-bedsheet-double',
    itemName: 'Bedsheet (Double)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'household-bedding-bedsheet-queen',
    itemName: 'Bedsheet (Queen)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'household-bedding-bedsheet-king',
    itemName: 'Bedsheet (King)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    seedKey: 'household-bedding-pillowcase',
    itemName: 'Pillowcase',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'household-bedding-pillow',
    itemName: 'Pillow',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    seedKey: 'household-bedding-duvet-cover',
    itemName: 'Duvet Cover',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 3500,
    priceHigh: 6000,
  },
  {
    seedKey: 'household-bedding-duvet',
    itemName: 'Duvet',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 3500,
    priceHigh: 6000,
  },
  {
    seedKey: 'household-bedding-comforter',
    itemName: 'Comforter',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'heavy',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 4200,
    priceHigh: 7800,
  },
  {
    seedKey: 'household-bedding-blanket-light',
    itemName: 'Blanket (Light)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 2000,
    priceHigh: 3000,
  },
  {
    seedKey: 'household-bedding-blanket-heavy',
    itemName: 'Blanket (Heavy)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'heavy',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 3000,
    priceHigh: 4000,
  },
  {
    seedKey: 'household-bedding-mattress-cover',
    itemName: 'Mattress Cover',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bedding',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'household-curtains-and-blinds-window-curtain-short',
    itemName: 'Window Curtain (Short)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'curtains-and-blinds',
    priceLow: 1500,
    priceHigh: 2000,
  },
  {
    seedKey: 'household-curtains-and-blinds-door-curtain-large',
    itemName: 'Door Curtain (Large)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'heavy',
    categoryKey: 'household',
    subCategoryKey: 'curtains-and-blinds',
    priceLow: 2000,
    priceHigh: 2500,
  },
  {
    seedKey: 'household-curtains-and-blinds-sheer-curtain',
    itemName: 'Sheer Curtain',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'curtains-and-blinds',
    priceLow: 2000,
    priceHigh: 3000,
  },
  {
    seedKey: 'household-curtains-and-blinds-blackout-curtain',
    itemName: 'Blackout Curtain',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'curtains-and-blinds',
    priceLow: 2500,
    priceHigh: 3500,
  },
  {
    seedKey: 'household-bathroom-towel-small',
    itemName: 'Towel (Small)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bathroom',
    priceLow: 400,
    priceHigh: 700,
  },
  {
    seedKey: 'household-bathroom-towel-medium',
    itemName: 'Towel (Medium)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bathroom',
    priceLow: 400,
    priceHigh: 700,
  },
  {
    seedKey: 'household-bathroom-towel-large-bath',
    itemName: 'Towel (Large/Bath)',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bathroom',
    priceLow: 800,
    priceHigh: 1200,
  },
  {
    seedKey: 'household-bathroom-bath-mat',
    itemName: 'Bath Mat',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bathroom',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'household-bathroom-bathrobe',
    itemName: 'Bathrobe',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'bathroom',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'household-kitchen-table-cloth',
    itemName: 'Table Cloth',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'kitchen',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'household-kitchen-kitchen-towel',
    itemName: 'Kitchen Towel',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'kitchen',
    priceLow: 400,
    priceHigh: 700,
  },
  {
    seedKey: 'household-kitchen-apron',
    itemName: 'Apron',
    serviceKey: 'wash-and-fold',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'kitchen',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'household-living-bedroom-cushions',
    itemName: 'Cushions',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'living-bedroom',
    priceLow: 300,
    priceHigh: 500,
  },
  {
    seedKey: 'household-living-bedroom-handkerchief',
    itemName: 'Handkerchief',
    serviceKey: 'cleaning',
    serviceTypeKey: 'basic',
    categoryKey: 'household',
    subCategoryKey: 'living-bedroom',
    priceLow: 100,
    priceHigh: 100,
  },
  {
    seedKey: 'special-bulky-bulky-items-sofa-cover',
    itemName: 'Sofa Cover',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'special-bulky',
    subCategoryKey: 'bulky-items',
    priceLow: 600,
    priceHigh: 1300,
  },
  {
    seedKey: 'special-bulky-bulky-items-carpet-small',
    itemName: 'Carpet (Small)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'special-bulky',
    subCategoryKey: 'bulky-items',
    priceLow: 2400,
    priceHigh: 3900,
  },
  {
    seedKey: 'special-bulky-bulky-items-carpet-medium',
    itemName: 'Carpet (Medium)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'special-bulky',
    subCategoryKey: 'bulky-items',
    priceLow: 4200,
    priceHigh: 6500,
  },
  {
    seedKey: 'special-bulky-bulky-items-carpet-large',
    itemName: 'Carpet (Large)',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'heavy',
    categoryKey: 'special-bulky',
    subCategoryKey: 'bulky-items',
    priceLow: 7200,
    priceHigh: 13000,
  },
  {
    seedKey: 'special-bulky-bulky-items-rug',
    itemName: 'Rug',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'special-bulky',
    subCategoryKey: 'bulky-items',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'special-bulky-bulky-items-chair-cover',
    itemName: 'Chair Cover',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'special-bulky',
    subCategoryKey: 'bulky-items',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'special-bulky-bulky-items-cushion-cover',
    itemName: 'Cushion Cover',
    serviceKey: 'wash-and-iron',
    serviceTypeKey: 'basic',
    categoryKey: 'special-bulky',
    subCategoryKey: 'bulky-items',
    priceLow: 500,
    priceHigh: 1000,
  },
  {
    seedKey: 'special-care-premium-care-silk-garment',
    itemName: 'Silk Garment',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 750,
    priceHigh: 1500,
  },
  {
    seedKey: 'special-care-premium-care-lace-garment',
    itemName: 'Lace Garment',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 750,
    priceHigh: 1500,
  },
  {
    seedKey: 'special-care-premium-care-embroidered-garment',
    itemName: 'Embroidered Garment',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 750,
    priceHigh: 1500,
  },
  {
    seedKey: 'special-care-premium-care-beaded-dress',
    itemName: 'Beaded Dress',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 1800,
    priceHigh: 3000,
  },
  {
    seedKey: 'special-care-premium-care-wedding-gown',
    itemName: 'Wedding Gown',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 15000,
    priceHigh: 30000,
  },
  {
    seedKey: 'special-care-premium-care-suit-with-special-treatment',
    itemName: 'Suit with Special Treatment',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 3750,
    priceHigh: 5250,
  },
  {
    seedKey: 'special-care-premium-care-leather-jacket',
    itemName: 'Leather Jacket',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 2250,
    priceHigh: 3750,
  },
  {
    seedKey: 'special-care-premium-care-suede-jacket',
    itemName: 'Suede Jacket',
    serviceKey: 'dry-cleaning',
    serviceTypeKey: 'premium',
    categoryKey: 'special-care',
    subCategoryKey: 'premium-care',
    priceLow: 2250,
    priceHigh: 3750,
  },
];
