// Representative slice for Phase 0 — the full ~250-item catalog import
// from the Google Sheet is a Phase 1 migration (see SeederService.seedItems).
export default [
  {
    itemName: 'T-Shirt',
    service: 'Wash & Fold',
    serviceType: 'Basic',
    category: 'Men',
    subCategory: 'Tops',
    priceLow: 500,
    priceHigh: 800,
  },
  {
    itemName: 'Shirt',
    service: 'Wash & Iron',
    serviceType: 'Basic',
    category: 'Men',
    subCategory: 'Tops',
    priceLow: 700,
    priceHigh: 1000,
  },
  {
    itemName: 'Trousers',
    service: 'Wash & Fold',
    serviceType: 'Basic',
    category: 'Men',
    subCategory: 'Bottoms',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    itemName: 'Dress',
    service: 'Dry Cleaning',
    serviceType: 'Premium',
    category: 'Women',
    subCategory: 'Dresses',
    priceLow: 1500,
    priceHigh: 2500,
  },
  {
    itemName: 'Blouse',
    service: 'Wash & Iron',
    serviceType: 'Basic',
    category: 'Women',
    subCategory: 'Tops',
    priceLow: 700,
    priceHigh: 1000,
  },
  {
    itemName: 'Skirt',
    service: 'Wash & Fold',
    serviceType: 'Basic',
    category: 'Women',
    subCategory: 'Bottoms',
    priceLow: 600,
    priceHigh: 900,
  },
  {
    itemName: 'Bedsheet',
    service: 'Wash & Fold',
    serviceType: 'Heavy',
    category: 'Household',
    subCategory: 'Bedding',
    priceLow: 1000,
    priceHigh: 1500,
  },
  {
    itemName: 'Duvet Cover',
    service: 'Wash & Fold',
    serviceType: 'Heavy',
    category: 'Household',
    subCategory: 'Bedding',
    priceLow: 2000,
    priceHigh: 3000,
  },
  {
    itemName: 'Sneakers',
    service: 'Cleaning',
    serviceType: 'Premium',
    category: 'Shoes',
    subCategory: 'Others',
    priceLow: 2500,
    priceHigh: 4000,
  },
  {
    itemName: 'Baby Onesie',
    service: 'Wash & Fold',
    serviceType: 'Basic',
    category: 'Baby',
    subCategory: 'Baby Items',
    priceLow: 400,
    priceHigh: 600,
  },
];
